https://plantuml.com/guide
Chapter 2 Class Diagram

@startuml

note as Visibility
<size:15><b>Visibility
Sets accessibility for the method or attribute

 - private
 + public
 # protected
 ~ packaged/default
end note

note as Inheritance
<size:15><b>Inheritance
These are shown as child and parent class

Represented by an open arrow "<|--" Dashes represent position
end note

note as Association
<size:15><b>Association
There is no dependency between these classes

Represented by a single line between to classes "--"
end note

note as Aggregation
<size:15><b>Aggregation
There is no dependency between these classes

Represented by an open diamond "o--"
end note

note as Composition
<size:15><b>Composition
When a child object wouldn't be able to exist without
its parent object

Represented by a closed diamond "*--"
end note

note as Multiplicity
<size:15><b>Multiplicity
Describes how many instances of one class can be connected
 to an instance of another class through a given association

Represented by:
0..1 Zero to one
n Specific number
0..* Zero to many
1..* One to many
m..n Specific number range
end note

@enduml
